// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiningProject.DataContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MiningProject.Migrations.TruckLocationDb
{
    [DbContext(typeof(TruckLocationDbContext))]
    partial class TruckLocationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MiningProject.Models.History", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("LocationID");

                    b.Property<long?>("TruckID");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("TruckID");

                    b.ToTable("History");
                });

            modelBuilder.Entity("MiningProject.Models.Location", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Longitude");

                    b.HasKey("ID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("MiningProject.Models.Truck", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TruckType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("MiningProject.Models.History", b =>
                {
                    b.HasOne("MiningProject.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.HasOne("MiningProject.Models.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckID");
                });
#pragma warning restore 612, 618
        }
    }
}
